server:
  port: 8080
  session:
    cookie:
      secure: true
spring.freemarker.template-loader-path: classpath:/ftl
spring.freemarker.suffix: .ftl

spring:
  profiles:
    active: default
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/localDb?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true